# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UserLoginAPI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.3'

  # Pods for UserLoginAPI

  target 'UserLoginAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UserLoginAPIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
